### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by heapwolf**
Adds a C++ tap library.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Please read and adhere to the [contributing guidelines](../blob/master/contributing.md).

**Comment by heapwolf** [comment]
@sindresorhus updated

**Comment by sindresorhus** [comment]
I don't see any difference. Please actually read the guidelines. There are multiple things not followed from it ;)

**Comment by heapwolf** [comment]
Just close it then

**Pull request closed without merging**
